dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
after_success:
- ./gradlew jacocoTestReport coveralls
- ./gradlew artifactoryPublish -PbintrayUsername="${BINTRAY_USER}" -PbintrayApiKey="${BINTRAY_KEY}"
env:
  global:
  - secure: L++Z5NPJwlkOSipGFpDAilTx8rkiCBS16/nW2wI0QBO4tN0P2uz/k2CksgPxfUWDYPBX7Tq33fnE+D6AGzGbt+aY157TasAPOQorrvO+JhxT1O8Sg3PNx035fJLqXJ/6vaxln5Gg+o3gapRZeGr+QAtHi7CH2XNbvzKpAaR3qTRdFwi1lD+FQuCJJEOGXOFs9UvHMyuIkeTW31hAYxUwhTbdr/KekpHx413Xhm6NqeqqsK1u1Ppcwgvc7bKagCrWW5InYj55VYliV1jGEXqCZVQ7tFwcNhXGg6bFD0JQ0St7L8OOwdxzbxMSXKtmFU2rBKmfl4Ex6Qyjd7QIrA2cbhv9EX0e0c1vcXyCK2Cup1CDAc7FknXbr3xeEOjs6+F180VzhPbR32iTOw0Q3EiFHm9u5YXzsi/CxiZFj9JHxBzD6nyquADHbxD48oHbD/eZjx5zjR0pjakla/6gAv96dXuYPp7MZveslWNY6hobkcq/HnxgyNpR60IwcqLOk90LD2C4W7hS7mBrqsj9Rcc+im3F8Nxmfhmq30oMVHP5RLBGKvg8ADVF62SyN99zEVDRhoyDtn8c1SQxHmvAv1ZKKTz5vw8iVsdNKm6hkcFS/Dzf1Gqr/ZYnJC/5VpK44SmcoWjNQTHdHrvJb6rPfFDG8ECeNk6hrKxLvUfSx2+9xBY=
  - secure: BbuBcF8OETr195YQnhyJ2ISv3JzWGt0xpGtZHcbNVWXGvaPaRZfipNekrE67lsYkP4MrqHYs++ve9Ocx61NBc4/Gy2oxkRk6FPcp8qZ9YjyaByodvZ3RuSmGHuknbQJzYtEqRhfU00Q2ZDQWbhUnDOXm4hn5JTLZt3+bPyRNCygO95MnRK/yJOdC67Lltv4VhQLm8Oz71GmMmiA2t60eJeWcLaGXMssPCB89mGkukB1K0qMou4+u0qKJqwqmmlnUvE9rpFiWKUx3RHJoiMsnKWcMbKoamLg7wbhQC16oCRbp+G/RmjlgttJeXIB/dlu/6NFyrKgvfkJVV1cSmHUE4CUeC28Sn+WfAd4vNlbd/mL89aWCzBQUE9WxZHwoOBA4LKgO5nud+etw9fWfMVw7J3Ncr2pSZkW5G2OVSnHq46hAp3dbaDkksF9UkRJd1l1JSRBuAk6+Rlk7ghVMzFadtIFyeMd2om3g9BQDUL3e7dZRxQ5pp2FDZRpHBELKeyFgtZxCxemKAa3Lmo0J1xHQvjJ/nHEP7IxG5PGMbqnDc/7yWpjAMwY07o7zNIojkgnnTB9BITSSUSE2mcWDyBvlc2YifhDVqqfm0RgOlXHc4z2/gFwa6mZS18enAHDOyPg/koZDNd9PBVEvNz4dtMD9g3YSjgEYuNGQ5U27jtj8/vk=
