= assertj-swagger
:author: Robert Winkler
:version: 0.1.0
:hardbreaks:

image:https://travis-ci.org/RobWin/assertj-swagger.svg["Build Status", link="https://travis-ci.org/RobWin/assertj-swagger"] image:https://coveralls.io/repos/RobWin/assertj-swagger/badge.svg?branch=master["Coverage Status", link="https://coveralls.io/r/RobWin/assertj-swagger"] image:https://api.bintray.com/packages/robwin/maven/assertj-swagger/images/download.svg[link="https://bintray.com/robwin/maven/assertj-swagger/_latestVersion"] image:http://img.shields.io/badge/license-ASF2-blue.svg["Apache License 2", link="http://www.apache.org/licenses/LICENSE-2.0.txt"]
image:https://badges.gitter.im/Join%20Chat.svg[link="https://gitter.im/RobWin/assertj-swagger?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]

== Overview

assertj-swagger is a https://github.com/joel-costigliola/assertj-core[assertj] library which compares a design-first https://github.com/swagger-api/swagger-spec[Swagger] YAML with an implementation-first Swagger JSON output (e.g. from https://github.com/springfox/springfox[springfox]).
assertj-swagger allows to validate that the implementation fits the design specification. The library supports Swagger Spec v2.

assertj-swagger compares Swagger objects like Paths, Parameters and Definitions. It does not compare __unimportant__ Swagger objects like info, descriptions or summaries.

== Usage guide

=== Adding assertj-swagger to your project
The project is not yet published in JCenter and Maven Central.

==== Maven

[source,xml]
----
<repositories>
    <repository>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
        <id>central</id>
        <name>bintray</name>
        <url>http://jcenter.bintray.com</url>
    </repository>
</repositories>

<dependency>
    <groupId>io.github.robwin</groupId>
    <artifactId>assertj-swagger</artifactId>
    <version>0.1.0</version>
</dependency>
----

==== Gradle

[source,groovy]
----
repositories {
    jcenter()
}

compile "io.github.robwin:assertj-swagger:0.1.0"
----

=== Using assertj-swagger in a unit test

[source, java]
----
@Test
public void validateThatImplementationFitsDesignSpecification(){
    String implFirstSwaggerLocation = SwaggerAssertTest.class.getResource("/wrong_swagger.json").getPath();
    String designFirstSwaggerLocation = SwaggerAssertTest.class.getResource("/swagger.yaml").getPath();
    SwaggerAssertions.assertThat(implFirstSwaggerLocation).isEqualTo(designFirstSwaggerLocation);
}
----

==== Example output

[source]
----
The following 4 assertions failed:
1) [Checking Paths]
Expecting:
  <["/pets", "/pets/findByError", "/pets/findByTags", "/pets/notDefiniedInSwaggerSpec", "/pets/{petId}", "/stores/order", "/stores/order/{orderId}", "/users", "/users/createWithArray", "/users/createWithList", "/users/login", "/users/logout", "/users/{username}"]>
to contain only:
  <["/pets", "/pets/findByStatus", "/pets/findByTags", "/pets/{petId}", "/stores/order", "/stores/order/{orderId}", "/users", "/users/createWithArray", "/users/createWithList", "/users/login", "/users/logout", "/users/{username}"]>
elements not found:
  <["/pets/findByStatus"]>
and elements not expected:
  <["/pets/findByError", "/pets/notDefiniedInSwaggerSpec"]>

2) [Checking 'DELETE' operation of path '/pets'] expected:<null> but was:<com.wordnik.swagger.models.Operation@515c6049>
3) [Checking 'POST' operation of path '/pets']
Expecting actual not to be null
4) [Checking 'produces' of 'GET' operation of path '/pets/findByTags']
Expecting:
  <["application/json"]>
to contain only:
  <["application/json", "application/xml"]>
but could not find the following elements:
  <["application/xml"]>
----

== License

Copyright 2015 Robert Winkler

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
